# Generated by Django 4.2.1 on 2023-05-31 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots/')),
                ('language', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('font', models.CharField(max_length=100)),
                ('font_size', models.IntegerField()),
                ('font_color', models.CharField(max_length=100)),
                ('screenshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_blocks', to='dddapi.screenshot')),
            ],
        ),
    ]
